//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCP.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class usb
    {
        public int id_usb { get; set; }
        public string numero_serie { get; set; }
        public float capacidad { get; set; }
        public string marca { get; set; }
        public int id_cliente { get; set; }
        public string nombre_cliente { get { return this.getClientName(); } }
        public string capacidad_string { get { return getCapacidad(); } }
        
        public virtual cliente cliente { get; set; }


        private string getClientName()
        {
            return this.cliente.nombre_cliente;
        }

        private string getCapacidad()
        {
            float capacidad =(float) Math.Ceiling((double)(this.capacidad));
            return capacidad.ToString() + " GB";
        }
    }
}
